### PR TITLE
Update 2 0 1

### PR DESCRIPTION
**Pull request by oolonek**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

First update of conda package hope I din't forget anything. Happy to learn :)

### CODE REVIEW

**Comment by mjsteinbaugh** [comment]
@oolonek , I'm happy to help with this, if there's anything I can do to help get the v2.0.1 release up.

**Comment by mjsteinbaugh** [comment]
@oolonek Yeah I'm not an expert on this either, and mainly contribute to bioconda. Maybe we should file an issue at [r-vroom-feedstock](https://github.com/conda-forge/r-vroom-feedstock)?

**Comment by izahn** [comment]
Thanks for helping with this @mjsteinbaugh and @oolonek! I think the problems are all in package dependencies rather than any problem with the recipe here. I suggest working with the maintainers to see if we can get https://github.com/conda-forge/r-readr-feedstock/pull/17 merged instead of this one.

**Comment by oolonek** [comment]
Closed as suggested by @izahn 
#17 should be the one to follow and accept

**Pull request closed without merging**
